[pytest]
markers =
    regression: full test suite
    smoke: critical tests
    login: authentication tests
    cart: cart related tests
    checkout: checkout tests
    ui: UI tests
    product: product related tests
    search: search functionality
    navigation: category/brand navigation